# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:466.0.0@sha256:5a15e9ada9e8f4780cead7276348332a47b547aa28f379fb733a4a9ecd556faf
RUN apt-get install -y netcat
